language: java
jdk: oraclejdk8
services: postgresql
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - psql -c 'create user "dynamicdb-test";' -U postgres
  - psql -c 'create database "dynamicdb-test" owner "dynamicdb-test";' -U postgres
